#!/bin/bash
#
# Copyright (C) 2017 Red Hat, Inc.  All Rights Reserved.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it would be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write the Free Software Foundation,
# Inc.,  51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#

#export SKIPTEST=1
[ -n "${SKIPTEST}" ] && echo "This test is currently unreliable due to backend recovery issues."

export FIO_VALIDATE_OPT="--runtime=90 --size=30G"

. ${LIB}/backend_generic
. ${LIB}/mpath_generic
. ${LIB}/failpath_nvme_offline
. ${LIB}/fio_validate

if [ "$MULTIPATH_BACKEND_MODULE" != "nvmefcloop" ]
then
	echo "Not using a NVMe backend"
	exit 2
fi

if [ "$MULTIPATH_QUEUE_MODE" != "bio" ]
then
	echo "Not using 'queue_mode bio'"
	exit 2
fi

create_mpath
start_failpath_nvme_offline

run_fio_validate
ret=$?

stop_failpath_nvme_offline
delete_mpath

exit $ret
