#!/bin/bash
#
# Copyright (C) 2015 NEC Corporation.  All Rights Reserved.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it would be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write the Free Software Foundation,
# Inc.,  51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#

. ${LIB}/backend_generic
. ${LIB}/mpath_generic
. ${LIB}/failpath_sdev_offline
. ${LIB}/fio_validate

create_mpath
start_failpath_sdev_offline

run_fio_validate
ret=$?

stop_failpath_sdev_offline
delete_mpath

exit $ret
