#!/bin/bash
#
# Copyright (C) 2015 NEC Corporation.  All Rights Reserved.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it would be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write the Free Software Foundation,
# Inc.,  51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#

backend_all_paths ()
{
        grep -l scsi_debug /sys/block/sd*/device/model | \
		awk -F/ '{print $4}'
}

backend_all_hosts ()
{
        grep -l scsi_debug /sys/class/scsi_host/host*/proc_name | \
		awk -F/ '{print $5}'
}

backend_create_device ()
{
	modprobe -r scsi_debug
	modprobe scsi_debug vpd_use_hostno=0 \
		dev_size_mb=1024 add_host=4 max_luns=1 \
		delay=1
}

backend_delete_device ()
{
	rmmod scsi_debug
}

