#!/bin/bash
#
# Copyright (C) 2015 NEC Corporation.  All Rights Reserved.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it would be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write the Free Software Foundation,
# Inc.,  51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#

stopfile=stop.failpath_sdev_offline

start_failpath_sdev_offline () {
	[ -z "$MPNAME" ] && exit 1
	local d
	local m
	local devs=$(mpath_all_paths)
	local majs=$(for d in $devs; do cat /sys/block/$d/dev; done)

	rm -f $stopfile
	while [ ! -f $stopfile ]; do
		for d in $devs; do
			echo offline > /sys/block/${d}/device/state
		done
		for d in $devs; do
			echo running > /sys/block/${d}/device/state
		done
		for m in $majs; do
			dmsetup message $MPNAME 0 "reinstate_path $m"
		done
	done &
}

stop_failpath_sdev_offline ()
{
	touch $stopfile
	wait
}
