#!/bin/bash
#
# Copyright (C) 2017 Red Hat, Inc.  All Rights Reserved.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it would be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write the Free Software Foundation,
# Inc.,  51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#

. ${LIB}/backend_nvmefcloop

stopfile=stop.failpath_nvme_offline

start_failpath_nvme_offline () {
    [ -z "$MPNAME" ] && exit 1
    local d
    local m
    local devs=$(mpath_all_paths)
    local majs=$(for d in $devs; do cat /sys/block/$d/dev; done)

    rm -f $stopfile
    while [ ! -f $stopfile ]; do
	    del_remote_ports

	    sleep 1

	    add_remote_ports

	    # can easily take 10 secs for devices to come back...
	    sleep 15

	    for m in $majs; do
		    dmsetup message $MPNAME 0 "reinstate_path $m"
	    done

	    sleep 2
    done &
}

stop_failpath_nvme_offline ()
{
    touch $stopfile
    wait
}
