#!/bin/bash
#
# Copyright (C) 2015 NEC Corporation.  All Rights Reserved.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it would be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write the Free Software Foundation,
# Inc.,  51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#

stopfile=stop.failpath_sdev_delete

_reload_mpath_table () {
        local table="$(mpath_table)"
        echo "$table" | dmsetup load $MPNAME && \
	dmsetup suspend --nolockfs --noflush $MPNAME && \
	dmsetup resume $MPNAME
}

start_failpath_sdev_delete () {
	[ -z "$MPNAME" ] && exit 1
	local d
	local h
	rm -f $stopfile
	while [ ! -f $stopfile ]; do
		for d in $(mpath_all_paths); do
			echo 1 > /sys/block/${d}/device/delete
		done
		#sleep 1
		for h in $(mpath_all_hosts); do
			echo '- - -' > /sys/class/scsi_host/${h}/scan
		done
		#sleep 1
		_reload_mpath_table
	done &
}

stop_failpath_sdev_delete ()
{
	touch $stopfile
	wait
	sleep 3
}
