#!/bin/bash
#
# Copyright (C) 2015 NEC Corporation.  All Rights Reserved.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it would be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write the Free Software Foundation,
# Inc.,  51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#

if [ -z "${FIO_VALIDATE_OPT}" ]; then
	FIO_VALIDATE_OPT="--runtime=30 --size=10G"
fi

run_fio_validate ()
{
	if [ -z "$MPNAME" ] || [ ! -b "/dev/mapper/$MPNAME" ]; then
		echo "FAILED TO START"
		return 1
	fi

	fio --bs=512k --rw=randwrite --direct=1 --iodepth=2 --ioengine=libaio \
	    --filename=/dev/mapper/$MPNAME --time_based ${FIO_VALIDATE_OPT} \
	    --do_verify=1 --verify=meta --verify_dump=1 --verify_fatal=1 \
	    --name=test1
	if [ $? -ne 0 ]; then
		echo "FAILED"
		return 1
	else
		echo "SUCCESS"
		return 0
	fi
}
