#!/bin/bash
#
# Copyright (C) 2015 NEC Corporation.  All Rights Reserved.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it would be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write the Free Software Foundation,
# Inc.,  51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#

stopfile=stop.switchpg_dm_message

start_switchpg_dm_message () {
	[ -z "$MPNAME" ] && exit 1

	rm -f $stopfile
	while [ ! -f $stopfile ]; do
		dmsetup message $MPNAME 0 "disable_group 1"
		sleep 1
		dmsetup message $MPNAME 0 "enable_group 1"
		sleep 1
	done &
}

stop_switchpg_dm_message ()
{
	touch $stopfile
	wait
}
